name: ${project.name}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}.ParticleGuidesPlugin
author: FreshLlamanade
api-version: 1.19
softdepend:
  - Essentials

permissions:
    particleguides.guide:
        description: Allows a player access to the /guide command
        default: op
    particleguides.guide.coords:
        description: Allows a player additional access to the /guide coords command
        default: op
        children:
          survivalhaven.guide: true
    particleguides.guide.death:
        description: Allows a player additional access to the /guide death command
        default: op
        children:
          survivalhaven.guide: true
    particleguides.guide.here:
        description: Allows a player additional access to the /guide here command
        default: op
        children:
          survivalhaven.guide: true
    particleguides.guide.home:
      description: Allows a player additional access to the /guide home command
      default: op
      children:
        survivalhaven.guide: true
    particleguides.guide.player:
        description: Allows a player additional access to the /guide player command
        default: op
        children:
          survivalhaven.guide: true
    particleguides.guide.*:
        description: Allows a player full access to the /guide command
        default: op
        children:
          survivalhaven.guide: true
          survivalhaven.guide.coords: true
          survivalhaven.guide.death: true
          survivalhaven.guide.here: true
          survivalhaven.guide.home: true
          survivalhaven.guide.player: true
    particleguides.breadcrumbs.*:
        description: Allows a player unlimited length access to the /breadcrumbs command
        default: op
    particleguides.admin:
        description: Allows a player to manage the plugin
        default: op
    particleguides.*:
        description: Allows a player full access to the plugin
        default: op
        children:
          survivalhaven.guide.*: true
          survivalhaven.breadcrumbs.*: true
          survivalhaven.admin: true
